[general]
#import = ["string"] Para importar ficheros toml de configuracion.
working_directory = "None"
live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "SourceCodePro"
style = "bold"

[font.bold_italic]
family = "SourceCodePro"
style = "Bold Italic"

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"

[window]
opacity = 0.95
blur = true
startup_mode = "Windowed" #Maximized|Fullscreen|Windowed
title = "Alacritty"
decorations_theme_variant = "None" #Dark|Light|None

[scrolling]
history = 500
multiplier = 3

[cursor]
style = "Block"
#Block|Underline|Beam

[mouse]
hide_when_typing = false

[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"
